import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import Navbar from "@/components/navbar";
import "./globals.css";


import { cn } from "@/lib/utils"
 
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
          "flex flex-row min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}>
        <div className="flex w-1/6">
        <Navbar/>
        </div>
        <div className="flex flex-col w-5/6 p-4">
        {children}
        
        </div>
        </body>
    </html>
  );
}
